### PR TITLE
Prevent addref for non-refcounted zvals

### PR DESCRIPTION
**Pull request by adsr**

### CODE REVIEW

**Comment by Sean-Der** [comment]
Oof, nice catch. Hopefully getting close to stable for you guys?

Would you mind replacing the conditionals with `Z_TRY_ADDREF_P`? Not a huge deal, but just a nice macro that keeps things terse.

thanks!

**Comment by adsr** [comment]
Nice, didn't know about `Z_TRY_ADDREF_P`. Thanks Sean!

**Comment by Sean-Der** [comment]
Rocking, merged!
Working on php-src beats any easter egg hunt, never know what you will find.

What me to make a new release with this patch?

**Comment by adsr** [comment]
Thanks for the quick merge Sean. No rush to cut a release. Already in prod on our end.

**Pull request merged**
